enabled: true
apply_on_enable: true
write_mode: write_if_drift
operating_mode: 0
return_delay_time: 0
maximum_acceleration: 254
startup_acceleration: 254
clear_phase_feedback_overflow_bit: true
pid:
  p: 16
  i: 0
  d: 32
overrides:
  gripper:
    max_torque_limit: 1000
    protection_current: 500
