DEFAULT_BAUDRATE = 1_000_000
DEFAULT_CONTROL_HZ = 200
DEFAULT_TRAJECTORY_INPUT_HZ = 60
DEFAULT_FEEDBACK_HZ = 100
DEFAULT_WEB_MOTION_HZ = 30
DEFAULT_WEB_STATE_HZ = 30
DEFAULT_WEB_RENDER_HZ = 60
DEFAULT_LOW_VOLTAGE = 7.0
DEFAULT_MAX_STEP_RAD = 0.75
DEFAULT_TIMEOUT_MARGIN = 2.0

POSITION_TICKS_PER_REVOLUTION = 4096
MIN_POSITION_TICK = 0
MAX_POSITION_TICK = 4095
MIDDLE_POSITION_TICK = 2048

MAX_SPEED_SETTING = 32767
DEFAULT_POSITION_SPEED = MAX_SPEED_SETTING
DEFAULT_POSITION_ACCELERATION = 254
